(SystemServiceHelper.java:56) java.lang.NoClassDefFoundError: android.telecom.TelecomManager Class requires API level 21 (current min is 16): android.telecom.TelecomManager I add this @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)